services:
  sensorpush:
    container_name: sensorpush-python
    hostname: sensorpush-python
    tty: true
    environment:
      CONFIG_SECRETS_FILE: /run/secrets/config_secrets
      PYTHONUNBUFFERED: 1
    image: sensorpush-python
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: on-failure:3
    secrets:
      - config_secrets
secrets:
  config_secrets:
    file: ./app/config/secrets.toml
