# Elastic Server Configuration
ES_USERNAME = "elastic"
ES_PASSWORD = "password"
ES_URL = "https://localhost:9200"
KB_URL = "https://localhost:5601"

# APM Configuration
APM_SECRET_TOKEN = "secret-token"
APM_SERVER_URL = "https://localhost:8200"

# App Configuration
SENSORPUSH_EMAIL = "yourname@domain.com"
SENSORPUSH_PASSWORD = "password"
