# Elastic configuration
INDEX_NAME = "delete-me"
DELETE_INDEX = true

# APM Configuration
APM_SERVICE_VERSION = "1.0"
APM_ENVIRONMENT = "Development"
APM_SERVICE_NAME = "sensorpush-refactor"

# SensorPush Configuration
DEFAULT_START_TIME = "2025-01-05:00:00.000Z"
AUTHENTICATE_URL = "https://api.sensorpush.com/api/v1/oauth/authorize"
AUTHORIZATION_URL = "https://api.sensorpush.com/api/v1/oauth/accesstoken"
GATEWAY_URL = "https://api.sensorpush.com/api/v1/devices/gateways"
SENSOR_URL = "https://api.sensorpush.com/api/v1/devices/sensors"
DATA_URL = "https://api.sensorpush.com/api/v1/samples"
DATA_LIMIT = 500
SLEEP_DURATION = 60
MEASURES = [
    "temperature",
    "humidity",
    "dewpoint",
    "barometric_pressure",
    "altitude",
]

# Sensor Configuration
[[SENSORS]]
id = "16786480.31759915751390790374"
name = "sensor1"
description = "Back Outdoor Sensor"

[[SENSORS]]
id = "16785468.27282632252927060817"
name = "sensor2"
description = "Office Sensor"

[[SENSORS]]
id = "16790861.31423968661707354582"
name = "sensor3"
description = "Family Room Sensor"

[[SENSORS]]
id = "16790976.41992679133619533343"
name = "sensor4"
description = "Front Outdoor Sensor"

[[SENSORS]]
id = "16781432.9249598422354522167"
name = "sensor5"
description = "Bedroom Sensor"

[[SENSORS]]
id = "16781414.4311703833465249174"
name = "sensor6"
description = "Living Room Sensor"

[[SENSORS]]
id = "16907598.18759925232750857632"
name = "sensor7"
description = "Basement Sensor"
