# Elastic configuration
INDEX_NAME = "sensorpush"
DELETE_INDEX = false

# APM Configuration
APM_SERVICE_VERSION = "1.0"
APM_ENVIRONMENT = "Development"
APM_SERVICE_NAME = "sensorpush"

# SensorPush Configuration
DEFAULT_START_TIME = "2024-12-01T00:00:00.000Z"
AUTHENTICATE_URL = "https://api.sensorpush.com/api/v1/oauth/authorize"
AUTHORIZATION_URL = "https://api.sensorpush.com/api/v1/oauth/accesstoken"
GATEWAY_URL = "https://api.sensorpush.com/api/v1/devices/gateways"
SENSOR_URL = "https://api.sensorpush.com/api/v1/devices/sensors"
DATA_URL = "https://api.sensorpush.com/api/v1/samples"
DATA_LIMIT = 500
SLEEP_DURATION = 60
MEASURES = ["temperature", "humidity", "dewpoint", "barometric_pressure", "altitude"]

# Sensor Configuration
[[SENSORS]]
id = "1234.1234"
name = "sensor-one"
description = "Sensor One"

[[SENSORS]]
id = "4567.4567"
name = "sensor-two"
description = "Sensor Two"
